env:
  CONAN_UPLOAD: https://api.bintray.com/conan/inexorgame/inexor-conan
  CONAN_BUILD_POLICY: outdated
  CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}

on: [push, pull_request]

jobs:
  MinGW:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mingwVersion: ["7", "8"]
        buildType: [Debug, Release]
        arch: [x86_64]
        threads: [posix]
        include:
          - arch: "x86_64"
            exceptions: seh
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: |
            pip install bincrafters_package_tools
      - name: run  
        env:
            CONAN_BUILD_TYPES: ${{matrix.buildType}}
            MINGW_CONFIGURATIONS: ${{matrix.mingwVersion}}@${{matrix.arch}}@${{matrix.exceptions}}@${{matrix.threads}}
            CONAN_BUILD_REQUIRES: "msys2/20161025"
        run: |
            bincrafters-package-tools --auto
